### ISSUE TITLE
Using the Internet for Social Capital through Timebanking

### ISSUE THREAD

**Issue by Amaris-AR** [MozillaFestival/mozfest-program-2018#744]
[ Session Name ] Using the Internet for Social Capital through Timebanking
[ Primary Space ] Youth Zone
[ Secondary Space ] Digital Inclusion
[ Submitter's Name ] Demond Drummer
[ Submitter's Affiliated Organisation ] CoderSpace
[ Other Facilitator 1's Name ] Amaris Alanis Ribeiro

[ Language ]
English
Spanish
Portuguese
[ Localisation Support Requested ] None

[ What will happen in your session? ]

STEM organizations often fall under the spell of an economic capital, but what if we centered what we do in social capital? Many STEM organizations engage communities (one-way directed) or have community members volunteer (still one-way directed), but what if we enacted upon the assets of communities and had reciprocal exchanges instead?
In this session participants will map assets/needs and learn the principles of timebanking. Timebanking is reciprocal exchange of services, skills, and goods through a timebank where the currency is an hour of time for everyone.
Example-
Problem: Many immigrants are learning to speak the language of their new home but need to build employment skills. How do we ensure the assets and skills of immigrants are used while building language and technology skills?
Solution: Let us timebank language lessons and have community members lead workshops such as woodworking, gardening, and nature art at the local nature center. 
Session leaders will share ideas around coding as social capital and how other STEM organizations have used timebanking. There were also be an opportunity map our various social economies and to hack ideas from various timebanks around the world.

[ What is the goal or outcome of your session? ]
1. Expose people to see the value in timebanking. 2. People can articulate what timebanking is and what it can mean for them/their organization. 3. Participants believe in the possibility of timebanking as a way to equitably engage communities. This session will inform a strategy to improve training, materials, the timebank and communications to talk about the shift to an asset-based, reciprocal exchange, and social economy.We also hope to see organizations join timebanks and have some documented examples of varied exchanges.

[ If your session requires additional materials or electronic equipment, please outline your needs. ]
Standard AV- Projector and video capabilities.

[ Time needed ]
60 mins

**Comment by Saallen** [comment]
Hi @Amaris-AR we cannot accept proposals directly through Github.
The call closed 5 days ago- did you apply through Open leaders?

**Comment by Amaris-AR** [comment]
Hi Sarah,

Thank you for your email. I'm sorry about the confusion. My
colleague Demond Drummer (copied) applied for Open Leaders and listed me as
a team member. I hope that is ok. I understand that you have a deadline and
completely respect that, we weren't sure where to describe the project
since Demond spoke more about CoderSpace in his application and we noticed
a link to include a project proposal.

Please let us know if there is anything we need to correct on our end.

Thanks,
Amaris

**Comment by Derds** [comment]
Hi Amaris,
Love the concept of timebanking, really interesting! Just wondering about the audience you intended for this? We have a lot of children and young people in Youthzone so I was just wondering if you had any ideas about how you would include them in this discussion or how you would align this session to that space?
Thanks,
Dervla

**Comment by Amaris-AR** [comment]
Hi Dervla,

We would be excited if children and young people attended the session!

We may start with some examples of youth engaging in timebanking. For
example, CoderSpace (my co-presenter Demond copied) is mobilizing the
social capital of youth to engage more young people in computer science
education. This is happening in a systemic and bureaucratic context where
financial capital has failed to deliver on the promise of Computer Science
for All (CS4All). In another example, learning time in the Computer Lab is
bartered for recreational time in the gym



Then we'd want to work with the youth to identify areas in their own
lives/schools/communitues/passions where financial capital has failed to
deliver and have them cratft solutions that moblize social capital.



We'd end the seession with them presenting their proposals to each other.

Thanks,
Amaris

**Comment by marcwalsh** [comment]
Thank you for taking the time to submit a session to MozFest.

Due to the high level of submissions, we’re unable to accept all proposals and unfortunately, your session was not part of the final group.

You'll receive a follow up email from us in the next few days.
